### PR TITLE
Fix loading state from other archs

### LINKED ISSUE #287: Cannot load state form different archs
**Describe the bug**
See also dusk-network/rusk#1043

**Possible solutions**
- Keep compilations outside the state (This can be handled upstream in rusk-recovery, removing the compiled file from the portable state, but we must be sure that piecrust is going to recompile it if it's missing)
- Recompile if the state if it's not build for the current architecture

### PR DESCRIPTION
**Pull request by ureeves**
We do this by at `VM` instantiation time, checking if the module is correct for the native platform. If the module is not correct we compile it and write it back to disk. 

Resolves #287

### CODE REVIEW

File: piecrust/src/store.rs [hunk 1]
```diff
@@ -196,6 +204,37 @@ fn commit_from_dir<P: AsRef<Path>>(dir: P) -> io::Result<Commit> {
             ));
         }
 
+        // TODO ensure that objectcode is valid for this platform, otherwise
```
Comment (herr-seppia) [inline piecrust/src/store.rs:207]: Errant?

**Review by herr-seppia — APPROVED** [review]
LGTM

How much overhead is this PR introducing?
Asking because I'm not sure if it worth to add the check as distinct function

File: piecrust/src/store.rs (hunk 1 above)
Comment (ureeves) [reply piecrust/src/store.rs]: Yes, fixed.
