### PR TITLE
Fix post-error root calculation 

### LINKED ISSUE #296: Inconsistent root after erroring calls
**Describe the bug**
The root is inconsistent after an erroring call.

**To Reproduce**
During the implementation of https://github.com/dusk-network/rusk/pull/1125, a test was added that makes an erroring call, and then subsequently executes another call. Another session is then instantiated that only runs successful calls, which then displays a different root than before.

**Expected behaviour**
Calls should be atomic - if they error nothing should be left behind.

### PR DESCRIPTION
**Pull request by ureeves**
Resolves #296

### CODE REVIEW

File: contracts/callcenter/src/lib.rs [hunk 1]
```diff
@@ -92,6 +92,11 @@ impl Callcenter {
         call_with_limit(contract, "spend", &(), points_limit)?;
         Ok(())
     }
+
+    /// Just panic.
+    pub fn panik(&self) {
```
Comment (moCello) [inline contracts/callcenter/src/lib.rs:97]:
```suggestion
    pub fn panic(&self) {
```

File: contracts/callcenter/src/lib.rs [hunk 2]
```diff
@@ -92,6 +92,11 @@ impl Callcenter {
...
+        panic!("panik");
```
Comment (moCello) [inline contracts/callcenter/src/lib.rs:98]:
```suggestion
        panic!("panic");
```

File: contracts/callcenter/src/lib.rs (hunk 1 above)
Comment (ureeves) [reply contracts/callcenter/src/lib.rs:97]: But I like to [`panik`](https://i.pinimg.com/originals/bd/ce/25/bdce2580f547211a9bbf43d04a9b50ff.jpg)

File: contracts/callcenter/src/lib.rs (hunk 2 above)
Comment (ureeves) [reply contracts/callcenter/src/lib.rs:98]: https://github.com/dusk-network/piecrust/pull/293#discussion_r1402114886

File: piecrust/src/session.rs [hunk 3]
```diff
@@ -451,47 +450,35 @@ impl Session {
...
     ///
-    /// If the contract does not exist, or is otherwise not instantiated in this
-    /// session, it will return `None`.
-    pub fn memory_len(&self, contract_id: &ContractId) -> Option<usize> {
-        self.instance(contract_id)
-            .map(|instance| instance.mem_len())
+    /// If the contract does not exist, it will return `None`.
+    pub fn memory_len(
+        &mut self,
+        contract_id: ContractId,
```
Comment (moCello) [inline piecrust/src/session.rs:456]: Is there a reason why this is changed to consume the `contract_id`?

**Review by moCello — APPROVED** [review]
LGTM

File: piecrust/src/session.rs (hunk 3 above)
Comment (ureeves) [reply piecrust/src/session.rs:456]: Yes. Previously it used the `WrappedInstance::mem_len` function internally, but now it uses `ContractSession::contract`. The latter takes a `ContractId` rather than a reference to it. It's essentially for the same reason as why we changed the return to be a `Result`.

This is kk though, since `ContractId` is pretty small and `Copy`.

**Review by herr-seppia — APPROVED** [review]
LGTM
